#:schema node_modules/wrangler/config-schema.json
name = "geo"
main = "src/index.ts"
compatibility_date = "2024-04-23"
compatibility_flags = ["nodejs_compat"]
minify = true

tail_consumers = [{ service = "geo-tail" }]

# Change this one to your custom domain
[[routes]]
pattern = "geo.srvr.dev"
custom_domain = true

# Specify a specific and fixed port for the local server
[dev]
port = 3000

# The CPU limit can be set to a maximum of 30,000 milliseconds (30 seconds).
[limits]
cpu_ms = 30

# Automatically place your workloads in an optimal location to minimize latency.
# If you are running back-end logic in a Worker, running it closer to your back-end infrastructure
# rather than the end user may result in better performance.
# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
[placement]
mode = "smart"

# The rate limiting API is in open beta.
[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
# An identifier you define, that is unique to your Cloudflare account.
# Must be an integer.
namespace_id = "1001"

# Limit: the number of tokens allowed within a given period in a single
# Cloudflare location
# Period: the duration of the period, in seconds. Must be either 10 or 60
simple = { limit = 5, period = 60 }
